### PR TITLE
Implement redecoration through changing the fields instead of transpiling

### PR DESCRIPTION
**Pull request by RedBrumbler**

### CODE REVIEW

**Comment by RedBrumbler** [comment]
Male tested it and it fixed the crash (and still works for things)

**Comment by RedBrumbler** [comment]
but I suppose I can do a more thorough test with qosmetics at a later point

**Comment by raineio** [comment]
Thorough tests are preferred, as this is a big change.

Let me know of the results, if issues arise and so forth.

**Comment by RedBrumbler** [comment]
Tested with Qosmetics Cyoobs, works completely fine

**Comment by raineio** [comment]
sounds good to me

**Pull request merged**
